version: '3'
services:
  db:
    image: postgres:9.6.18-alpine
    volumes:
      - ./web/tmp/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    command: bundle exec puma
    build:
      context: .
      args:
        - "R_ENV=development"
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
