version: '3'
services:
  db:
    image: postgres:9.6.18-alpine
    volumes:
      - ./web/tmp/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    volumes:
      - ./web:/web
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
