version: '3'
services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - ./web/tmp/db:/var/lib/postgresql
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
    networks:
      - blabla_network
  web:
    command: bundle exec puma
    build:
      context: .
      args:
        - "R_ENV=development"
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    links:
      - db:db
    networks:
      - blabla_network

networks:
  blabla_network:
    driver: bridge
